### ISSUE TITLE
To release audio in free format

### ISSUE THREAD

**Issue by muchweb** [NathanEpstein/How_To_Start_A_Startup#1]
MP3 is a nasty restricted format, because it is impeded by software patents in some countries.

The Ogg Vorbis is free format, it's specification is in the public domain, technologically superior to MP3, and it is not encumbered by patents.

Related:
- [Why Audio Format Matters](http://www.gnu.org/philosophy/why-audio-format-matters.html)
- [PlayOgg!](http://playogg.org/)

**Comment by afomi** [comment]
@muchweb, `.ogg` files are available through the Archive.org pages that are linked to in the README.md.
