### ISSUE TITLE
Put up unzipped files for mobile

### ISSUE THREAD

**Issue by marcuswestin** [NathanEpstein/How_To_Start_A_Startup#2]
Hey,

If the files were unzipped, would I be able to listen to them on my phone straight from the website? If yes, that would be fantastic.

Thanks for putting this together!

**Comment by NathanEpstein** [comment]
Marcus,

The repo now has links to direct downloads of the mp3's which (I believe)
you should be able to get on your phone. Glad you enjoyed!

Best,

Nathan Epstein
(973) 985 - 8158
LinkedIn https://www.linkedin.com/in/ne2210 | Github
https://github.com/nathanepstein | Technical Blog
https://medium.com/@Epstein_N/latest

**Comment by marcuswestin** [comment]
Thanks dude!
